/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Utils.Cmd;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeDebug.getClass;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Francisco 
 */
public class Planeta extends javax.swing.JFrame {

   // public String up;
    
    
    private String senha = "123";
    private String senhaPacote = "teste1234";

    /**
     * Creates new form Planeta
     */
    ButtonGroup bG;
    public static Integer up;
    public static Integer at;
     
      
    public Planeta() {
        initComponents();
        painel_secundario.setVisible(false);
               
    }
    
    public void imagemIcon(){
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("nb333re.png"));
            
        label1.setIcon(img);
       }
    
     
    public void nb805teIcon(){
        ImageIcon img = new ImageIcon(getClass().getResource("nb805te1.png")); 
        
        label1.setIcon(img);
        }
    public void nb805mcIcon(){
        ImageIcon img = new ImageIcon(getClass().getResource("nb805mc.png"));
        label1.setIcon(img);
    }
     public void nb364phIcon(){
        ImageIcon img = new ImageIcon(getClass().getResource("nb364ph1.png")); //nb805te1.png
        
        label1.setIcon(img);
        }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_primario = new javax.swing.JPanel();
        btn_combo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label_titulo1 = new javax.swing.JLabel();
        btn_verificar = new javax.swing.JToggleButton();
        label1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_setup = new javax.swing.JToggleButton();
        txt_senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        painel_secundario = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_download = new javax.swing.JToggleButton();
        label_gif = new javax.swing.JLabel();
        btn_voltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnPacote = new javax.swing.JButton();
        txt_senha1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("V-04-02-2022");

        painel_primario.setBackground(new java.awt.Color(255, 255, 255));
        painel_primario.setToolTipText("");

        btn_combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma das opções", "NB333RE", "NB805TE", "NB805MC", "NB364PH" }));
        btn_combo1.setToolTipText("");
        btn_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combo1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel1.setText("MODELO");

        label_titulo1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        label_titulo1.setText("VERIFICAR APLICATIVOS");

        btn_verificar.setBackground(new java.awt.Color(0, 0, 255));
        btn_verificar.setForeground(new java.awt.Color(235, 235, 235));
        btn_verificar.setText("VERIFICAR");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        label1.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/multilaser.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setText("SENHA:");

        btn_setup.setBackground(new java.awt.Color(0, 0, 255));
        btn_setup.setForeground(new java.awt.Color(235, 235, 235));
        btn_setup.setText("INICIAR");
        btn_setup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setupActionPerformed(evt);
            }
        });

        jLabel7.setText("DESENVOLVIMENTO: ENGENHARIA DE PRODUTO");

        javax.swing.GroupLayout painel_primarioLayout = new javax.swing.GroupLayout(painel_primario);
        painel_primario.setLayout(painel_primarioLayout);
        painel_primarioLayout.setHorizontalGroup(
            painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_primarioLayout.createSequentialGroup()
                .addGroup(painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_primarioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label1))
                    .addGroup(painel_primarioLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btn_verificar)))
                .addGap(84, 84, 84))
            .addGroup(painel_primarioLayout.createSequentialGroup()
                .addGroup(painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_primarioLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(painel_primarioLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_setup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel_primarioLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_primarioLayout.createSequentialGroup()
                .addGap(0, 299, Short.MAX_VALUE)
                .addComponent(label_titulo1)
                .addGap(206, 206, 206))
        );
        painel_primarioLayout.setVerticalGroup(
            painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_primarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo1)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_verificar)
                .addGap(44, 44, 44)
                .addGroup(painel_primarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btn_setup, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5))
        );

        painel_secundario.setBackground(new java.awt.Color(255, 255, 255));
        painel_secundario.setForeground(new java.awt.Color(255, 255, 255));

        label_titulo.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        label_titulo.setText("CHECK APP");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/multilaser.png"))); // NOI18N

        btn_download.setText("VERIFICAR APLICATIVOS");
        btn_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_downloadActionPerformed(evt);
            }
        });

        btn_voltar.setBackground(new java.awt.Color(0, 0, 255));
        btn_voltar.setForeground(new java.awt.Color(235, 235, 235));
        btn_voltar.setText("NOVO");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        jLabel5.setText("DESENVOLVIMENTO: ENGENHARIA DE PRODUTO");

        jLabel8.setText("GERAR PACOTE DE APLICATIVOS:");

        btnPacote.setBackground(new java.awt.Color(0, 0, 255));
        btnPacote.setForeground(new java.awt.Color(235, 235, 235));
        btnPacote.setText("START");
        btnPacote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacoteActionPerformed(evt);
            }
        });

        jLabel2.setText("SENHA:");

        javax.swing.GroupLayout painel_secundarioLayout = new javax.swing.GroupLayout(painel_secundario);
        painel_secundario.setLayout(painel_secundarioLayout);
        painel_secundarioLayout.setHorizontalGroup(
            painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_secundarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(334, 334, 334))
            .addGroup(painel_secundarioLayout.createSequentialGroup()
                .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_secundarioLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(label_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_secundarioLayout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(btn_voltar))
                            .addGroup(painel_secundarioLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(btn_download, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painel_secundarioLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painel_secundarioLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPacote))))))
                    .addGroup(painel_secundarioLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        painel_secundarioLayout.setVerticalGroup(
            painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_secundarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label_titulo)
                .addGap(222, 222, 222)
                .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_secundarioLayout.createSequentialGroup()
                        .addComponent(btn_download)
                        .addGap(18, 18, 18)
                        .addComponent(btn_voltar)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8))
                    .addComponent(label_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel_secundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnPacote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel_secundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painel_primario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_secundario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(painel_primario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel_primario.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("Desenvolvidao por: Engenharia de Produto 01--2-2020");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combo1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_combo1ActionPerformed

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        if(btn_combo1.getSelectedItem().equals("Selecione uma das opções")){
            JOptionPane.showMessageDialog(null, "Opção invalida!", null, WIDTH);
        }
        else if(btn_combo1.getSelectedItem().equals("NB333RE")){
            imagemIcon();
            label_titulo1.setText("NB333RE");
            label_titulo.setText("NB333RE");
            up = 1;           
        }
        else if(btn_combo1.getSelectedItem().equals("NB805TE")){
            nb805teIcon();
            label_titulo.setText("NB805TE");
            label_titulo1.setText("NB805TE");
            up = 2;
        }
        else if(btn_combo1.getSelectedItem().equals("NB805MC")){
            nb805mcIcon();
            label_titulo.setText("NB805MC");
            label_titulo1.setText("NB805MC");
            up = 3;
        }
        else if(btn_combo1.getSelectedItem().equals("NB364PH")){
            nb364phIcon();
            label_titulo.setText("NB364PH");
            label_titulo1.setText("NB364PH");
            up = 4;
        }
    }//GEN-LAST:event_btn_verificarActionPerformed

    private void btn_setupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setupActionPerformed
            if(new String(txt_senha.getPassword()).equals(senha)){
                if(btn_combo1.getSelectedItem().equals("NB333RE")){
                    up = 1;
                    imagemIcon();
                    try {
                        Cmd.AtualizarScript(btn_setup.getActionCommand());
                    } catch (IOException ex) {
                        Logger.getLogger(Planeta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    painel_primario.setVisible(false);
                    painel_secundario.setVisible(true);
                    CardLayout card = (CardLayout)painel_secundario.getLayout();
                }
                
                else if(btn_combo1.getSelectedItem().equals("NB805TE")){
                    up = 2;
                    nb805teIcon();
                    try {
                        Cmd.AtualizarScript(btn_setup.getActionCommand());
                    } catch (IOException ex) {
                        Logger.getLogger(Planeta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    painel_primario.setVisible(false);
                    painel_secundario.setVisible(true);
                    CardLayout card = (CardLayout)painel_secundario.getLayout();
                }
                else if(btn_combo1.getSelectedItem().equals("NB805MC")){
                    up = 3;
                    nb805mcIcon();
                    try {
                        Cmd.AtualizarScript(btn_setup.getActionCommand());
                    } catch (IOException ex) {
                        Logger.getLogger(Planeta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    painel_primario.setVisible(false);
                    painel_secundario.setVisible(true);
                    CardLayout card = (CardLayout)painel_secundario.getLayout();
                }
                else if(btn_combo1.getSelectedItem().equals("NB364PH")){
                    up = 4;
                    nb364phIcon();
                    try {
                        Cmd.AtualizarScript(btn_setup.getActionCommand());
                    } catch (IOException ex) {
                        Logger.getLogger(Planeta.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    painel_primario.setVisible(false);
                    painel_secundario.setVisible(true);
                    CardLayout card = (CardLayout)painel_secundario.getLayout();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Modelo não cadastrado!");
                }
            }
            else{
                    JOptionPane.showMessageDialog(null, "Senha incorreta!");
            }
    }//GEN-LAST:event_btn_setupActionPerformed
    
    private void btn_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_downloadActionPerformed
        Path caminho = Paths.get("C:\\ComparaApp\\app.txt");
        Path caminho1 = Paths.get("C:\\ComparaApp\\root.txt");
                try {
                    byte[] texto = Files.readAllBytes(caminho);
                    byte[] texto1 = Files.readAllBytes(caminho1);
                    String root = new String(texto1);
                    String leitura = new String(texto);
                    
                    int r = root.compareTo(leitura);
                   
                    if(r == 0) {
                        String ok = ("APLICATIVOS OK!");
                        JOptionPane.showMessageDialog(null, ok,"Sucesso",JOptionPane.INFORMATION_MESSAGE);
                                   
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"ERRO NO PACOTE DE APLICATIVOS!","Falha",JOptionPane.ERROR_MESSAGE);
                 
                    }
                                                           
                }catch(Exception erro){
                                       
            }
                     
    }//GEN-LAST:event_btn_downloadActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        painel_primario.setVisible(true);
        painel_secundario.setVisible(false);
        CardLayout card = (CardLayout)painel_primario.getLayout();
    }//GEN-LAST:event_btn_voltarActionPerformed

    private void btnPacoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacoteActionPerformed
        // TODO add your handling code here:
        if(new String(txt_senha1.getPassword()).equals(senhaPacote)){
            try {
                Cmd.CriarPacote(btnPacote.getActionCommand());
                String ok = ("Pacote root.txt gerado!");
                        JOptionPane.showMessageDialog(null, ok,"Sucesso",JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(Planeta.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        }
    }//GEN-LAST:event_btnPacoteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planeta().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPacote;
    private javax.swing.JComboBox<String> btn_combo1;
    private javax.swing.JToggleButton btn_download;
    private javax.swing.JToggleButton btn_setup;
    private javax.swing.JToggleButton btn_verificar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label_gif;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_titulo1;
    private javax.swing.JPanel painel_primario;
    private javax.swing.JPanel painel_secundario;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JPasswordField txt_senha1;
    // End of variables declaration//GEN-END:variables
}

